### PR TITLE
Build Projector as a multi-arch image

### PR DESCRIPTION
**Pull request by mhuster23**
Adds support for arm64.

### CODE REVIEW

**Review by slisson — CHANGES_REQUESTED** [review]
I would not put anything modelix specific into this repository. I think the only required change in this repository is to add a parameter in build-container-dev.sh for the target platforms.

**Comment by mhuster23** [comment]
To use it in the other build it's required to tag and push the image in the same buildx build command.
However it should be possible to move the build command to the modelix buildscript and to not use any scripts from this repository.
If you prefer that approach, you may close this PR.

**Comment by slisson** [comment]
There is already a parameter for providing the tag name. It's fine to run the command with `--push` if a target platform is provided. I just want a clean interface for this repository that is not Modelix specific, but still adds multi platform support.

**Comment by slisson** [comment]
Right now images are always pushed. I still want to be able to build a local version for my current platform. If the third parameter is not specified, run the original command without `--push` and `--platform` parameters.

**Comment by mhuster23** [comment]
For perfomance reasons it might be better to use the regular `build` instead of buildx for local single-platform images.
Another flaw with the current solution is that it only allows for a single tag, since each tag has to be specified with `-t` adding additional tags on multi-platform images outside of the `buildx build` command is not possible. Is a single tag sufficient? If not, invoking `buildx build` directly in the modelix build script instead might be more elegant imo.

**Comment by slisson** [comment]
The script will be added to the modelix/modelix repo instead.

**Pull request closed without merging**
